export const GET_JOURNALS = 'GET_LOURNALS';
export const JOURNALS_ERROR = "JOURNALS_ERROR";
export const SET_LOADING = 'SET_LOADING';
export const COMMENTS_ERROR = 'COMMENTS_ERROR';
export const GET_COMMENTS = 'GET_COMMENTS';


